--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DanteDEVS/MurderMysteryLED
build-by-default: true
branches:
- main
projects:
  MurderMysteryLED:
    path: ""
    icon: "logo.png"
    libs:
      - src: Vecnavium/FormsUI/FormsUI
        version: ^1.1.2
...
