name: MurderMysteryLED
version: 2.2-PM4
api: [4.0.0]
author: LeyKey
main: mm\MurderMystery

commands:
  murdermystery:
    description: "Murder Mystery command"
    aliases: [mm, mrd]
    permission: "murdermystery.edit"
    
permissions:
  murdermystery.edit:
    description: "Permission to all Setup Commands!"
    default: op
